## MASUKKAN LIBRARY YANG DIGUNAKAN

In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [52]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pjbac\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

## LOAD DATASET

In [53]:
data = pd.read_csv('dataset_transkrip_ujiportfolio1.csv', encoding='Windows-1252')
data.head()

,teks,label
0,"iya siap pak, masih masih di situ Pak surat pe...",0
1,"siap, siap Pak, hari ini saya lengkapi foto be...",0
2,"izin Pak, untuk sekarang saya di bagian pelaya...",0
3,iya administrasi Pak tapi posisinya sudah tida...,1
4,ini level 2 kalau nggak salah Pak petugas lapa...,1


## TEXT PREPROCESSING

## CASE FOLDING

In [54]:
import re

# membuat fungsi untuk case folding
def casefolding(text):
    text = text.lower()                                 # mengubah text menjadi huruf kecil
    text = re.sub(r'https?://\S+|www\.S+', '', text)    # menghapus url dari kalimat
    text = re.sub(r'[^\w\s]', '', text)                 # menghapus tanda baca
    text = text.strip()
    return text

In [55]:
# membandingkan before dan after casefolding
raw_sample = data['teks'].iloc[2]
case_folding = casefolding(raw_sample)

print('Raw data\t : ',raw_sample)
print('Case Folding\t : ',case_folding)

Raw data	 :  izin Pak, untuk sekarang saya di bagian pelayanan pelanggan Pak untuk surat tidak ada sih Pak kalau untuk sekarang untuk penetapan untuk kami disini seluruhnya sudah di bagian transaksi energi Pak P2TL pernah Pak, pernah ikut untuk bulan Maret kemarin Pak ini kebetulan saya ada surat tugasnya enggak ada untuk surat tugas
mungkin saya sudah foto karena untuk penetapan sekarang semua sudah murni dari transaksi energi Pak jadi kami mungkin bagian pelayanan pelanggan itu hanya melobby saja ke pelanggan, mungkin ada pelanggan yang komplain, itu kami ke sana untuk bantu media menetapkan ya, halo siap, baik Pak, halo halo Pak tidak hadir pertama kali panggilan, selanjutnya apa? untuk kita kirimkan surat panggilan Pak, ya ya
pertama enggak datang, terus selanjutnya?
terus kita teruskan lagi untuk surat panggilan kedua
pertama dan kedua itu jaraknya berapa hari?
untuk jaraknya satu minggu Pak saya masih mengikuti yang perdir 88 untuk perdir baru saya belum dapat sih Pak terus pangg

## WORD NORMALIZATION

In [56]:
key_norm = pd.read_csv('key_norm.csv')

def text_normalize(text):
    text = ' '.join([key_norm[key_norm['singkat'] == word]['hasil'].values[0]
    if (key_norm['singkat'] == word).any()
    else word for word in text.split()
    ])

    text = str.lower(text)
    return text

In [57]:
# membandingkan before dan after word normalization

raw_data = data['teks'].iloc[2]
word_normal = text_normalize(case_folding)

print('Raw Data\t :',raw_data)
print('Word Normalize\t :',word_normal)

Raw Data	 : izin Pak, untuk sekarang saya di bagian pelayanan pelanggan Pak untuk surat tidak ada sih Pak kalau untuk sekarang untuk penetapan untuk kami disini seluruhnya sudah di bagian transaksi energi Pak P2TL pernah Pak, pernah ikut untuk bulan Maret kemarin Pak ini kebetulan saya ada surat tugasnya enggak ada untuk surat tugas
mungkin saya sudah foto karena untuk penetapan sekarang semua sudah murni dari transaksi energi Pak jadi kami mungkin bagian pelayanan pelanggan itu hanya melobby saja ke pelanggan, mungkin ada pelanggan yang komplain, itu kami ke sana untuk bantu media menetapkan ya, halo siap, baik Pak, halo halo Pak tidak hadir pertama kali panggilan, selanjutnya apa? untuk kita kirimkan surat panggilan Pak, ya ya
pertama enggak datang, terus selanjutnya?
terus kita teruskan lagi untuk surat panggilan kedua
pertama dan kedua itu jaraknya berapa hari?
untuk jaraknya satu minggu Pak saya masih mengikuti yang perdir 88 untuk perdir baru saya belum dapat sih Pak terus panggi

## STOPWORD REMOVAL (FILTERING)

In [58]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

stopwords_ind = stopwords.words('indonesian')

In [59]:
len(stopwords_ind)

758

In [60]:
# melihat daftar stopwords dari nltk
stopwords_ind

['ada',
 'adalah',
 'adanya',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhir',
 'akhiri',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'antara',
 'antaranya',
 'apa',
 'apaan',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'artinya',
 'asal',
 'asalkan',
 'atas',
 'atau',
 'ataukah',
 'ataupun',
 'awal',
 'awalnya',
 'bagai',
 'bagaikan',
 'bagaimana',
 'bagaimanakah',
 'bagaimanapun',
 'bagi',
 'bagian',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'baik',
 'bakal',
 'bakalan',
 'balik',
 'banyak',
 'bapak',
 'baru',
 'bawah',
 'beberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'bekerja',
 'belakang',
 'belakangan',
 'belum',
 'belumlah',
 'benar',
 'benarkah',
 'benarlah',
 'berada',
 'berakhir',
 'berakhirlah',
 'berakhirnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'berarti',
 'berawal',
 'berbagai',
 'berdatangan',
 'beri',
 'berikan',
 'berikut'

In [61]:
# membuat fungsi stopword removal

# menambahkan kata ke dalam stopword
more_stopword = ['ya', 'iya', 'nih', 'mas', 'nah', 'piak', 'sih', 'nya', 'serta', 'untuk', 'oh', 'loh', 'mana', 'si', 'eh', 'ln']
stopwords_ind = stopwords_ind + more_stopword

# daftar kata yang tidak boleh dihapus meskipun ada di stopword
exception_words = ['tidak', 'enggak', 'nggak', 'belum']

def remove_stop_word(text):
    clean_words = []
    text = text.split()
    for word in text:
        # hanya hapus jika kata ada di stopword dan bukan exception
        if word not in stopwords_ind or word in exception_words:
            clean_words.append(word)
    return " ".join(clean_words)

In [62]:
raw_sample = data['teks'].iloc[6]
case_folding = casefolding(raw_sample)
word_normal = text_normalize(case_folding)
stopword_removal = remove_stop_word(word_normal)

print('Raw Data \t\t :', raw_sample)
print('Case Folding \t\t :', case_folding)
print('Word Normalize \t\t :',word_normal)
print('Stop Word Removal \t\t :', stopword_removal)

Raw Data 		 : mohon izin Pak yang terbaru peraturan direksi nomor 28 tahun 2023 kalau tidak salah Pak mohon maaf Pak, ini betul Pak nomor 28 tahun 2023 tanggal 5 September Pak oke Pak Ronald untuk surat panggilan surat panggilan 1 itu jaraknya berapa Pak? panggilan kedua
30 hari Pak belum baca semua Pak panjang banget panggilan 1 panggilan kedua mungkin nanti saya coba belum tau Pak untuk jarak panggilan 1, panggilan kedua
mohon izin, mohon maaf saya belum tau Pak tapi biasanya kalau, bukan biasanya, saya kalau ada apa namanya kegiatan P2TL begitu Pak, saya lebih banyak membaca langsung ke apa namanya peraturan direksinya karena kalau saya hafal nanti Pak saya takut lupa pembongkaran pembongkaran langsung panggilan 3
panggilan 3 itu pembongkaran langsung pemutusan sementara
pemutusan sementara
sudah waktu panggilan 1 sudah putus pembongkaran Rampung itu setelah pelanggan
tidak membayar tagihannya ada surat apa itu sebelumnya?
ada surat panggilan panggilan pertama kedua dan ketiga
ada l

## STEMMING

In [63]:
!pip -q install sastrawi


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [64]:
# mengubah kata menjadi kata dasar
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

# membuat fungsi untuk stemming bahasa indonesia
def stemming(text):
    text = stemmer.stem(text)
    return text

In [65]:
raw_data = data['teks'].iloc[100]
case_folding = casefolding(raw_sample)
word_normal = text_normalize(case_folding)
stopword_removal = remove_stop_word(word_normal)
text_stemming = stemming(stopword_removal)

print('Raw Data \t\t :', raw_sample)
print('Case Folding \t\t :', case_folding)
print('Word Normalize \t\t :',word_normal)
print('Stop Word Removal \t\t :', stopword_removal)
print('Stemming \t\t :', text_stemming)

Raw Data 		 : mohon izin Pak yang terbaru peraturan direksi nomor 28 tahun 2023 kalau tidak salah Pak mohon maaf Pak, ini betul Pak nomor 28 tahun 2023 tanggal 5 September Pak oke Pak Ronald untuk surat panggilan surat panggilan 1 itu jaraknya berapa Pak? panggilan kedua
30 hari Pak belum baca semua Pak panjang banget panggilan 1 panggilan kedua mungkin nanti saya coba belum tau Pak untuk jarak panggilan 1, panggilan kedua
mohon izin, mohon maaf saya belum tau Pak tapi biasanya kalau, bukan biasanya, saya kalau ada apa namanya kegiatan P2TL begitu Pak, saya lebih banyak membaca langsung ke apa namanya peraturan direksinya karena kalau saya hafal nanti Pak saya takut lupa pembongkaran pembongkaran langsung panggilan 3
panggilan 3 itu pembongkaran langsung pemutusan sementara
pemutusan sementara
sudah waktu panggilan 1 sudah putus pembongkaran Rampung itu setelah pelanggan
tidak membayar tagihannya ada surat apa itu sebelumnya?
ada surat panggilan panggilan pertama kedua dan ketiga
ada l

## TEXT PREPROCESSING PIPELINE

In [66]:
# membuat fungsi untuk menghubungkan seluruh langkah text preprocessing
def text_preprocessing_process(text):
    text = casefolding(text)
    text = text_normalize(text)
    text = remove_stop_word(text)
    text = stemming(text)
    return text


In [67]:
%%time
data['clean_teks'] = data['teks'].apply(text_preprocessing_process)

CPU times: total: 8min 7s
Wall time: 8min 10s


In [68]:
data

,teks,label,clean_teks
0,"iya siap pak, masih masih di situ Pak surat pe...",0,situ surat tugas isi berita acara belum isi la...
1,"siap, siap Pak, hari ini saya lengkapi foto be...",0,lengkap foto belum kancing 028 028 2023 2023 j...
2,"izin Pak, untuk sekarang saya di bagian pelaya...",0,izin layan langgan surat tidak tetap transaksi...
3,iya administrasi Pak tapi posisinya sudah tida...,1,administrasi posisi tidak tangan p2tl join tau...
4,ini level 2 kalau nggak salah Pak petugas lapa...,1,level 2 tidak salah tugas lapang dokumen krusi...
...,...,...,...
291,"S1, Pak. Untuk sekarang karena sudah MULP, jad...",1,s1 mulp temu temanteman lapang administrasi ko...
292,Dari SMK Pak. Gimana Pak? Kalau saya Ibu melak...,1,smk p2tl surat tugas surat tugas bukti berita ...
293,"Masih, Pak. Ini untuk sebagai penanggung jawab...",1,tanggung butuh benarbenar oke bu langgan berat...
294,"Tadi sertifikasi kompetensi, surat tugas, sura...",1,sertifikasi kompetensi surat tugas surat kekat...


In [69]:
# simpan data yang sudah dilakukan preprocessing ke dalam file csv
data.to_csv('clean_data_asesmen.csv')

## FEATURE ENGINEERING

In [70]:
# pisahkan kolom feature dan target
x = data['clean_teks']
y = data['label']

In [71]:
x

0      situ surat tugas isi berita acara belum isi la...
1      lengkap foto belum kancing 028 028 2023 2023 j...
2      izin layan langgan surat tidak tetap transaksi...
3      administrasi posisi tidak tangan p2tl join tau...
4      level 2 tidak salah tugas lapang dokumen krusi...
                             ...                        
291    s1 mulp temu temanteman lapang administrasi ko...
292    smk p2tl surat tugas surat tugas bukti berita ...
293    tanggung butuh benarbenar oke bu langgan berat...
294    sertifikasi kompetensi surat tugas surat kekat...
295    fakta integritas oke p2tl surat tugas kirim su...
Name: clean_teks, Length: 296, dtype: object

In [72]:
y

0      0
1      0
2      0
3      1
4      1
      ..
291    1
292    1
293    1
294    1
295    1
Name: label, Length: 296, dtype: int64

## FEATURE EXTRACTION MENGGUNAKAN TF-IDF DAN N-GRAM

In [73]:
# save model
import pickle

#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

# Unigram
vec_TF_IDF = TfidfVectorizer(ngram_range=(1,2))
vec_TF_IDF.fit(x)

x_tf_idf = vec_TF_IDF.transform(x)

pickle.dump(vec_TF_IDF,open("feature_tf-idf_asesmen.pkl", "wb"))

In [74]:
# menampilkan vocabulary dari TF-IDF
vec_TF_IDF.vocabulary_

{'situ': 17656,
 'surat': 18168,
 'tugas': 20294,
 'isi': 7235,
 'berita': 3294,
 'acara': 707,
 'belum': 3031,
 'langsung': 10325,
 'ini': 7111,
 'meriksa': 12105,
 'dokumen': 5353,
 'dokumendokumen': 5383,
 'ba': 2305,
 'izin': 7327,
 'masuk': 11715,
 'lokasi': 11260,
 'langgar': 10194,
 'temu': 18972,
 'hasil': 6544,
 'periksa': 14892,
 'langgan': 9860,
 'datang': 4802,
 'selesai': 17032,
 'kantor': 8111,
 'bawa': 2759,
 'serah': 17183,
 'administrasi': 905,
 'banya': 2610,
 'barang': 2643,
 'bukti': 3835,
 'lapang': 10465,
 'segel': 16874,
 'rusak': 16419,
 'gantung': 6254,
 'posisi': 15519,
 'mcb': 11879,
 'b1': 2241,
 'level': 10933,
 'laksana': 9660,
 'cari': 4063,
 'kali': 8011,
 'tidak': 19419,
 'hitung': 6687,
 'nama': 12531,
 'ketemu': 8818,
 'bagi': 2455,
 'teman': 18877,
 'khusus': 8866,
 'penting': 14717,
 'sma': 17798,
 'terima': 19215,
 'baru': 2666,
 'alam': 1114,
 'jenis': 7647,
 'situ surat': 17731,
 'surat tugas': 18214,
 'tugas isi': 20360,
 'isi berita': 7245,
 'b

In [75]:
# melihat jumlah feature
print(len(vec_TF_IDF.get_feature_names_out()))

21356


In [76]:
# melihat fitur-fitur apa saja yang ada di dalam corpus
print(vec_TF_IDF.get_feature_names_out())

['00' '00 008' '0023' ... 'zoom' 'zp' 'zp dir']


In [77]:
x1 = vec_TF_IDF.transform(x).toarray()
data_tabular_tf_idf = pd.DataFrame(x1,columns=vec_TF_IDF.get_feature_names_out())
data_tabular_tf_idf

,00,00 008,0023,0023 0163,0023 perdir,0028,0028 0028,0028 2023,0028 app,0028 atur,...,yuk tetangga,yuk tidak,yuridiksi,yuridiksi ngerenah,zaman,zaman error,zaman tl,zoom,zp,zp dir
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
292,0.0,0.0,0.0,0.0,0.0,0.047636,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
293,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
294,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [78]:
data_tabular_tf_idf.iloc[10:20,60:70]

,0028 tip,0028 titik,0028p,0028p langgan,007,007 dir,008,008 00,008 008,008 088
10,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.050407,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0


## FEATURE SELECTION

In [79]:
x_train = np.array(data_tabular_tf_idf)
y_train = np.array(y)

In [81]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

chi2_feature = SelectKBest(chi2, k=10000)
x_kbest_features = chi2_feature.fit_transform(x_train, y_train)

# untuk reduce feature
print('original feature number', x_train.shape[1])
print('reduce feature number', x_kbest_features.shape[1])

original feature number 21356
reduce feature number 10000


In [83]:
Data = pd.DataFrame(chi2_feature.scores_,columns=['Nilai'])
Data

,Nilai
0,0.325768
1,0.325768
2,1.337499
3,0.668750
4,0.668750
...,...
21351,0.012594
21352,0.019388
21353,0.251533
21354,0.605032


In [84]:
# menampilkan data feature beserta nilainya
feature = vec_TF_IDF.get_feature_names_out()
feature

Data['Fitur'] = feature
Data

,Nilai,Fitur
0,0.325768,00
1,0.325768,00 008
2,1.337499,0023
3,0.668750,0023 0163
4,0.668750,0023 perdir
...,...,...
21351,0.012594,zaman error
21352,0.019388,zaman tl
21353,0.251533,zoom
21354,0.605032,zp


In [85]:
# mengurutkan nilai fitur terbaik
Data.sort_values(by='Nilai', ascending=False)

,Nilai,Fitur
193,9.783851e+00,088
14789,7.131900e+00,perdir 088
382,4.483731e+00,2016
196,3.859301e+00,088 2016
664,3.848017e+00,88
...,...,...
16487,7.565114e-07,sadap kabel
18058,7.050253e-07,stm
10965,5.169841e-07,level laksana
7562,2.120178e-07,jarak panggil


In [86]:
mask = chi2_feature.get_support()
mask

array([ True,  True,  True, ...,  True,  True,  True], shape=(21356,))

In [87]:
# menampilkan fitur yang terpilih berdasarkan nilai mask atau nilai tertinggi yang sudah ditetapkan pada chi square
new_feature=[]
for bool, f in zip(mask, feature):
    if bool :
        new_feature.append(f)
    selected_feature = new_feature
selected_feature

['00',
 '00 008',
 '0023',
 '0023 0163',
 '0023 perdir',
 '0028',
 '0028 0028',
 '0028 2023',
 '0028 app',
 '0028 baca',
 '0028 baru',
 '0028 belum',
 '0028 damping',
 '0028 dokumen',
 '0028 garing',
 '0028 izin',
 '0028 jenis',
 '0028 kait',
 '0028 kompetensi',
 '0028 lain',
 '0028 laku',
 '0028 langgan',
 '0028 langgar',
 '0028 lengkap',
 '0028 masingmasing',
 '0028 masuk',
 '0028 mbak',
 '0028 mengevolasi',
 '0028 nonpelanggan',
 '0028 oke',
 '0028 organisasi',
 '0028 p2tl',
 '0028 panggil',
 '0028 perdir',
 '0028 sementara',
 '0028 serahin',
 '0028 sesuai',
 '0028 tanda',
 '0028 tip',
 '0028 titik',
 '0028p',
 '0028p langgan',
 '007',
 '007 dir',
 '008',
 '008 00',
 '008 008',
 '008 088',
 '008 dir',
 '008 ke2023',
 '0088',
 '0088 perdir',
 '0088 polisi',
 '0088z',
 '0088z baru',
 '008z',
 '008z bacabaca',
 '008z baru',
 '008z layan',
 '01',
 '0163',
 '0163 0088',
 '02',
 '02 ohm',
 '028',
 '028 028',
 '028 10',
 '028 2023',
 '028 app',
 '028 awalawal',
 '028 baca',
 '028 baru',
 '

In [88]:
# membuat vocabulary baru berdasarkan fitur yang terseleksi

new_selected_feature = {}

for (k,v) in vec_TF_IDF.vocabulary_.items():
    if k in selected_feature:
        new_selected_feature[k]=v

new_selected_feature

{'situ': 17656,
 'surat': 18168,
 'isi': 7235,
 'berita': 3294,
 'acara': 707,
 'belum': 3031,
 'ini': 7111,
 'meriksa': 12105,
 'dokumen': 5353,
 'dokumendokumen': 5383,
 'ba': 2305,
 'izin': 7327,
 'masuk': 11715,
 'lokasi': 11260,
 'temu': 18972,
 'hasil': 6544,
 'periksa': 14892,
 'langgan': 9860,
 'datang': 4802,
 'selesai': 17032,
 'serah': 17183,
 'administrasi': 905,
 'barang': 2643,
 'bukti': 3835,
 'lapang': 10465,
 'segel': 16874,
 'rusak': 16419,
 'posisi': 15519,
 'mcb': 11879,
 'b1': 2241,
 'level': 10933,
 'kali': 8011,
 'tidak': 19419,
 'hitung': 6687,
 'ketemu': 8818,
 'teman': 18877,
 'penting': 14717,
 'terima': 19215,
 'alam': 1114,
 'jenis': 7647,
 'situ surat': 17731,
 'surat tugas': 18214,
 'tugas isi': 20360,
 'isi berita': 7245,
 'berita acara': 3296,
 'acara belum': 724,
 'belum isi': 3057,
 'isi langsung': 7259,
 'langsung ini': 10369,
 'ini meriksa': 7118,
 'meriksa dokumen': 12106,
 'dokumen situ': 5376,
 'situ berita': 17670,
 'acara dokumendokumen': 739,


In [89]:
len(new_selected_feature)

10000

In [90]:
# simpan vectorizer
pickle.dump(new_selected_feature,open("new_selected_feature_tf-idf_asesmen.pkl","wb"))

In [91]:
# menampilkan fitur-fitur yang sudah diseleksi

data_selected_feature = pd.DataFrame(x_kbest_features, columns=selected_feature)
data_selected_feature

,00,00 008,0023,0023 0163,0023 perdir,0028,0028 0028,0028 2023,0028 app,0028 baca,...,yuk,yuk istilah,yuk langgan,yuk tetangga,yuk tidak,zaman,zaman tl,zoom,zp,zp dir
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
292,0.0,0.0,0.0,0.0,0.0,0.047636,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
293,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
294,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


## MODELLING

In [92]:
selected_x = x_kbest_features
selected_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(296, 10000))

In [93]:
# import library
import random
from sklearn.model_selection import train_test_split

# import algoritma XGBoost
from xgboost import XGBClassifier

In [95]:
x = selected_x
y = data.label

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


In [96]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(296, 10000))

In [97]:
y

0      0
1      0
2      0
3      1
4      1
      ..
291    1
292    1
293    1
294    1
295    1
Name: label, Length: 296, dtype: int64

In [98]:
# menampilkan jumlah data training dan data testing
print('Banyaknya X_train : ', len(x_train))
print('Banyaknya X_test : ', len(x_test))
print('Banyaknya Y_train : ', len(y_train))
print('Banyaknya Y_test : ', len(y_test))

Banyaknya X_train :  236
Banyaknya X_test :  60
Banyaknya Y_train :  236
Banyaknya Y_test :  60


In [99]:
# Proses training menggunakan XGBoost
text_algorithm = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')

In [100]:
model = text_algorithm.fit(x_train, y_train)

c:\Users\pjbac\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:199: UserWarning: [09:00:39] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


## EVALUASI MODEL

In [101]:
# input library yang dibutuhkan untuk proses testing
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

predicted = model.predict(x_test)

CM = confusion_matrix(y_test, predicted)

print(classification_report(y_test, predicted))
print(confusion_matrix(y_test, predicted))

              precision    recall  f1-score   support

           0       1.00      0.82      0.90        11
           1       0.96      1.00      0.98        49

    accuracy                           0.97        60
   macro avg       0.98      0.91      0.94        60
weighted avg       0.97      0.97      0.97        60

[[ 9  2]
 [ 0 49]]


In [102]:
# menyimpan model
pickle.dump(model,open("model_asesmen.sav", "wb"))

In [103]:
import pandas as pd
import numpy as np
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from xgboost import XGBClassifier

# === Data Preparation ===
x = data['clean_teks']
y = data['label']

# === Pipeline: TF-IDF + Chi2 Feature Selection + XGBoost ===
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(ngram_range=(1,2))), # feature extraction
    ('select', SelectKBest(chi2, k=10000)),   # feature selection
    ('clf', XGBClassifier(use_label_encoder=False, eval_metric='mlogloss'))
])

# Split data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# Train pipeline
pipeline.fit(x_train, y_train)

# Evaluate
y_pred = pipeline.predict(x_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

# Save pipeline
with open("pipeline_asesmen.pkl", "wb") as f:
    pickle.dump(pipeline, f)


              precision    recall  f1-score   support

           0       0.91      0.91      0.91        11
           1       0.98      0.98      0.98        49

    accuracy                           0.97        60
   macro avg       0.94      0.94      0.94        60
weighted avg       0.97      0.97      0.97        60

[[10  1]
 [ 1 48]]


c:\Users\pjbac\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:199: UserWarning: [09:00:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
